## Stage données L'équipe  -- TEST FILE

### Amaury Fournier

In [41]:
import pandas as pd
import numpy as np
import random
import re
import pandas as pd
from os import listdir
from os.path import isfile, join,getsize
import datetime
import csv
import pickle
import json
import smtplib
import pandas_profiling
import chardet
#path = "C:\Users\Data Science 5\Desktop\L_equipe"
path = "W:\L_equipe"
pd.set_option('display.max_columns', None)

In [6]:
#df = pd.read_pickle(path+'\dataframes\s_dataframe_general_xiti_pages_juin2015_partie2.pkl')
df = pd.read_csv(r"V:\Tables_Sas\L_Equipe\Projet_01042016\tables_brutes\Sessions\sessions_xiti-20151215-_Sessions_EQ_20151215.csv", sep=';')
#df_bas = pd.read_pickle(path+"\s_dataframe_general_xiti_clients.pkl")

In [7]:
df

,fileid,id_site,id_client,id_campagne,id_session,debut_de_session,fin_de_session,pages_vues,localisation_1er_niveau,localisation_2eme_niveau,localisation_3eme_niveau,terminal,os
0,_Sessions_EQ_20151215.csv,496306,1459274,NaN,1850162,2015-12-15 09:04:25,2015-12-15 09:04:25,1,Andorre,andorra la vella,Andorra la vella,Apple,iOS 9.1
1,_Sessions_EQ_20151215.csv,496306,1609829,NaN,3805682,2015-12-15 01:05:12,2015-12-15 01:05:12,1,Andorre,andorra la vella,Andorra la vella,Apple,iOS 9.2
2,_Sessions_EQ_20151215.csv,496306,74806,NaN,5817601,2015-12-15 20:36:35,2015-12-15 20:46:26,4,Andorre,andorra la vella,Andorra la vella,Apple,iOS 9.1
3,_Sessions_EQ_20151215.csv,496306,1609829,NaN,3805742,2015-12-15 15:48:38,2015-12-15 15:48:38,1,Andorre,andorra la vella,Andorra la vella,Apple,iOS 9.2
4,_Sessions_EQ_20151215.csv,496307,476208,NaN,1074182,2015-12-15 19:49:57,2015-12-15 19:49:57,1,Andorre,andorra la vella,Andorra la vella,Apple,iOS 7.1
5,_Sessions_EQ_20151215.csv,496307,476208,NaN,872762,2015-12-15 18:10:49,2015-12-15 18:10:49,1,Andorre,andorra la vella,Andorra la vella,Apple,iOS 7.1
6,_Sessions_EQ_20151215.csv,496307,476208,NaN,944422,2015-12-15 18:51:29,2015-12-15 18:51:29,1,Andorre,andorra la vella,Andorra la vella,Apple,iOS 7.1
7,_Sessions_EQ_20151215.csv,496307,1297394,NaN,1038901,2015-12-15 19:29:20,2015-12-15 19:29:34,2,Andorre,la massana,Arinsal,Apple,iOS 9.2
8,_Sessions_EQ_20151215.csv,496307,1297394,NaN,96151,2015-12-15 02:08:29,2015-12-15 02:08:29,1,Andorre,la massana,Arinsal,Apple,iOS 9.2
9,_Sessions_EQ_20151215.csv,496307,1297394,NaN,842631,2015-12-15 17:42:07,2015-12-15 17:42:07,1,Andorre,la massana,Arinsal,Apple,iOS 9.2
10,_Sessions_EQ_20151215.csv,496307,1297394,NaN,421781,2015-12-15 09:31:38,2015-12-15 09:31:38,1,Andorre,la massana,Arinsal,Apple,iOS 9.2
11,_Sessions_EQ_20151215.csv,496307,1297394,NaN,1738521,2015-12-15 22:43:08,2015-12-15 22:45:05,8,Andorre,la massana,Arinsal,Apple,iOS 9.2
12,_Sessions_EQ_20151215.csv,496307,1297394,NaN,1215701,2015-12-15 20:34:42,2015-12-15 20:34:42,1,Andorre,la massana,Arinsal,Apple,iOS 9.2
13,_Sessions_EQ_20151215.csv,496307,1297394,NaN,363891,2015-12-15 08:30:46,2015-12-15 08:36:54,20,Andorre,la massana,Arinsal,Apple,iOS 9.2
14,_Sessions_EQ_20151215.csv,496307,1279834,NaN,895721,2015-12-15 18:16:43,2015-12-15 18:16:43,1,Emirats Arabes Unis,dubayy,Dubai,Apple,iOS 9.2
15,_Sessions_EQ_20151215.csv,496307,975195,NaN,788542,2015-12-15 16:29:34,2015-12-15 16:29:34,1,Emirats Arabes Unis,dubayy,Dubai,Apple,iOS 9.1
16,_Sessions_EQ_20151215.csv,496307,1576421,NaN,98382,2015-12-15 02:28:51,2015-12-15 02:28:56,2,Emirats Arabes Unis,dubayy,Dubai,Apple,iOS 9.0
17,_Sessions_EQ_20151215.csv,496307,975195,NaN,1023082,2015-12-15 19:28:36,2015-12-15 19:28:36,1,Emirats Arabes Unis,dubayy,Dubai,Apple,iOS 9.1
18,_Sessions_EQ_20151215.csv,496307,1460876,NaN,1299581,2015-12-15 20:57:05,2015-12-15 20:57:05,1,Emirats Arabes Unis,dubayy,Dubai,Apple,iOS 9.2
19,_Sessions_EQ_20151215.csv,496307,1120162,NaN,551012,2015-12-15 12:40:50,2015-12-15 12:40:52,2,Emirats Arabes Unis,dubayy,Dubai,Apple,iOS 9.1
20,_Sessions_EQ_20151215.csv,496306,226387,NaN,8366941,2015-12-15 23:43:05,2015-12-15 23:43:13,15,Emirats Arabes Unis,dubayy,Dubai,Apple,iOS 9.2
21,_Sessions_EQ_20151215.csv,496306,310331,NaN,778412,2015-12-15 05:14:57,2015-12-15 05:22:40,15,Emirats Arabes Unis,dubayy,Dubai,Apple,iOS 8.1
22,_Sessions_EQ_20151215.csv,496307,975195,NaN,788552,2015-12-15 17:08:56,2015-12-15 17:08:56,1,Emirats Arabes Unis,dubayy,Dubai,Apple,iOS 9.1
23,_Sessions_EQ_20151215.csv,496307,1680556,NaN,224781,2015-12-15 06:56:02,2015-12-15 06:56:04,3,Emirats Arabes Unis,dubayy,Dubai,Apple,iOS 9.2
24,_Sessions_EQ_20151215.csv,496307,975195,NaN,370092,2015-12-15 08:46:07,2015-12-15 08:48:57,6,Emirats Arabes Unis,dubayy,Dubai,Apple,iOS 9.1
25,_Sessions_EQ_20151215.csv,496307,1120162,NaN,120872,2015-12-15 04:08:00,2015-12-15 04:10:48,9,Emirats Arabes Unis,dubayy,Dubai,Apple,iOS 9.1
26,_Sessions_EQ_20151215.csv,496307,975195,NaN,1022952,2015-12-15 18:22:11,2015-12-15 18:25:06,5,Emirats Arabes Unis,dubayy,Dubai,Apple,iOS 9.1
27,_Sessions_EQ_20151215.csv,496307,975195,NaN,828082,2015-12-15 17:40:09,2015-12-15 17:40:09,1,Emirats Arabes Unis,dubayy,Dubai,Apple,iOS 9.1
28,_Sessions_EQ_20151215.csv,496307,1292665,NaN,1257052,2015-12-15 20:49:36,2015-12-15 20:49:36,1,Emirats Arabes Unis,dubayy,Dubai,Apple,iOS 9.1
29,_Sessions_EQ_20151215.csv,496307,1292665,NaN,610912,2015-12-15 13:40:52,2015-12-15 13:41:34,4,Emirats Arabes Unis,dubayy,Dubai,Apple,iOS 9.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
221294,_Sessions_EQ_20151215.csv,496306,1656740,NaN,5296811,2015-12-15 19:40:40,2015-12-15 20:00:12,28,Mauritanie,nouakchott,Nouakchott,Apple,iOS 9.0
221295,_Sessions_EQ_20151215.csv,496306,1656740,NaN,8081511,2015-12-15 23:15:19,2015-12-15 23:15:51,5,Mauritanie,nouakchott,Nouakchott,Apple,iOS 9.0
221296,_Sessions_EQ_20151215.csv,496306,1100473,NaN,7709522,2015-12-15 22:40:40,2015-12-15 22:49:11,5,Mauritanie,nouakchott,Nouakchott,Apple,iOS 8.3
221297,_Sessions_EQ_20151215.csv,496306,1656740,NaN,1992081,2015-12-15 09:34:43,2015-12-15 09:36:22,10,Mauritanie,nouakchott,Nouakchott,Apple,iOS 9.0
221298,_Sessions_EQ_20151215.csv,496306,772071,NaN,3454942,2015-12-15 14:30:35,2015-12-15 14:30:35,1,Mauritanie,nouakchott,Nouakchott,Apple,iOS 9.2
221299,_Sessions_EQ_20151215.csv,496306,1656740,NaN,4007231,2015-12-15 16:26:28,2015-12-15 16:31:01,13,Mauritanie,nouakchott,Nouakchott,Apple,iOS 9.0
221300,_Sessions_EQ_20151215.csv,496306,1100473,NaN,7207742,2015-12-15 22:16:44,2015-12-15 22:27:46,16,Mauritanie,nouakchott,Nouakchott,Apple,iOS 8.3
221301,_Sessions_EQ_20151215.csv,496306,1656740,NaN,2611271,2015-12-15 11:56:31,2015-12-15 11:56:33,3,Mauritanie,nouakchott,Nouakchott,Apple,iOS 9.0
221302,_Sessions_EQ_20151215.csv,496306,1100473,NaN,2639222,2015-12-15 12:02:58,2015-12-15 12:09:55,5,Mauritanie,nouakchott,Nouakchott,Apple,iOS 8.3
221303,_Sessions_EQ_20151215.csv,496306,1656740,NaN,16421,2015-12-15 00:01:11,2015-12-15 00:05:01,21,Mauritanie,nouakchott,Nouakchott,Apple,iOS 9.0
221304,_Sessions_EQ_20151215.csv,496306,1100473,NaN,2922112,2015-12-15 12:52:39,2015-12-15 12:52:39,1,Mauritanie,nouakchott,Nouakchott,Apple,iOS 8.3
221305,_Sessions_EQ_20151215.csv,496306,1656740,NaN,7216701,2015-12-15 22:15:26,2015-12-15 22:33:45,50,Mauritanie,nouakchott,Nouakchott,Apple,iOS 9.0
221306,_Sessions_EQ_20151215.csv,496306,1100473,NaN,1941662,2015-12-15 09:23:32,2015-12-15 09:30:04,13,Mauritanie,nouakchott,Nouakchott,Apple,iOS 8.3
221307,_Sessions_EQ_20151215.csv,496306,1656740,NaN,432221,2015-12-15 01:36:54,2015-12-15 01:40:46,14,Mauritanie,nouakchott,Nouakchott,Apple,iOS 9.0
221308,_Sessions_EQ_20151215.csv,496306,772071,NaN,6491382,2015-12-15 21:30:14,2015-12-15 21:30:14,1,Mauritanie,nouakchott,Nouakchott,Apple,iOS 9.2
221309,_Sessions_EQ_20151215.csv,496306,1656740,NaN,3532171,2015-12-15 14:44:09,2015-12-15 14:44:13,3,Mauritanie,nouakchott,Nouakchott,Apple,iOS 9.0
221310,_Sessions_EQ_20151215.csv,496306,1566166,NaN,5484842,2015-12-15 20:06:31,2015-12-15 20:06:31,1,Mauritanie,nouakchott,Nouakchott,Apple,iOS 7.1
221311,_Sessions_EQ_20151215.csv,496306,1100473,NaN,303842,2015-12-15 00:54:25,2015-12-15 00:54:32,3,Mauritanie,nouakchott,Nouakchott,Apple,iOS 8.3
221312,_Sessions_EQ_20151215.csv,496306,772071,NaN,6208402,2015-12-15 21:10:33,2015-12-15 21:10:33,1,Mauritanie,nouakchott,Nouakchott,Apple,iOS 9.2
221313,_Sessions_EQ_20151215.csv,496306,1566166,NaN,3972212,2015-12-15 16:23:36,2015-12-15 16:23:38,2,Mauritanie,nouakchott,Nouakchott,Apple,iOS 7.1
221314,_Sessions_EQ_20151215.csv,496306,409802,NaN,235092,2015-12-15 00:37:58,2015-12-15 00:37:58,1,Myanmar,yangon,Rangoon,Apple,iOS 8.3
221315,_Sessions_EQ_20151215.csv,496306,1707026,NaN,5039832,2015-12-15 19:11:55,2015-12-15 19:12:04,2,Serbie,belgrade,Belgrade,Apple,iOS 9.2
221316,_Sessions_EQ_20151215.csv,496306,1707026,NaN,5416992,2015-12-15 19:58:25,2015-12-15 20:01:38,5,Serbie,belgrade,Belgrade,Apple,iOS 9.2
221317,_Sessions_EQ_20151215.csv,496306,1707026,NaN,5902092,2015-12-15 20:46:06,2015-12-15 20:46:06,1,Serbie,belgrade,Belgrade,Apple,iOS 9.2
221318,_Sessions_EQ_20151215.csv,496306,1707026,NaN,5039822,2015-12-15 00:25:03,2015-12-15 00:25:03,1,Serbie,belgrade,Belgrade,Apple,iOS 9.2
221319,_Sessions_EQ_20151215.csv,496306,1568137,NaN,4063581,2015-12-15 16:37:18,2015-12-15 16:37:18,1,Soudan du sud,central equatoria,Juba,Apple,iOS 9.1
221320,_Sessions_EQ_20151215.csv,496306,1568137,NaN,907161,2015-12-15 06:16:50,2015-12-15 06:16:50,2,Soudan du sud,central equatoria,Juba,Apple,iOS 9.1
221321,_Sessions_EQ_20151215.csv,496306,1568137,NaN,4121591,2015-12-15 16:48:07,2015-12-15 16:48:07,1,Soudan du sud,central equatoria,Juba,Apple,iOS 9.1
221322,_Sessions_EQ_20151215.csv,496306,1568137,NaN,3011361,2015-12-15 13:05:28,2015-12-15 13:05:30,2,Soudan du sud,central equatoria,Juba,Apple,iOS 9.1
221323,_Sessions_EQ_20151215.csv,496306,1568137,NaN,4803831,2015-12-15 18:36:30,2015-12-15 18:36:30,1,Soudan du sud,central equatoria,Juba,Apple,iOS 9.1

In [39]:
now = datetime.datetime.now()
now = datetime.datetime(2015,4,15,23,10)
#if now.hour >= 1 and now.hour <5 : print 'yes'
#if now.hour> 14 : print 'maybe'
#if now.hour> 13 : print 'no'
if now.hour < 0 : print "yes"
print now.time()

23:10:00

### Session

In [43]:
name = "s_dataframe_pages_juin2015_partie2.pkl"
reg = re.match((".*_pages_(.*)\.pkl"), name)
print reg.group(1)

juin2015_partie2

In [ ]:
df.ServiceTitle = df.ServiceTitle.str.normalize("NFKD")
df.ServiceTitle = df.ServiceTitle.str.encode('ASCII','ignore')
df.loc[df.ServiceTitle.str.contains('Coca')]
#print len(df.ServiceTitle.value_counts(dropna=False))
#df.ServiceTitle.value_counts(dropna=False)

In [3]:
#affiche la totalité des colonnes du dataframe
pd.set_option('display.max_columns', None)

#retourne la liste des csv du répertoire Y:\L_Equipe\tablesbrutes\root\namedir
def makelistcsv(namedir, root):
    path = r'Y:\L_Equipe\tablesbrutes' + "\\" + root +"\\"+ namedir 
    if root == "Ventes en ligne":
        onlyfiles = [join(path,f) for f in listdir(path) if isfile(join(path, f)) if f.endswith('.csv') if f.startswith('EQP') if getsize(join(path,f))>0]
    else :
        onlyfiles = [join(path,f) for f in listdir(path) if isfile(join(path, f)) if f.endswith('.csv') if getsize(join(path,f))>0]
    return onlyfiles

#construit le dataframe du csv
def makedataframe(csv):
    if 'Ventes en ligne' in csv :
        df = pd.read_csv(csv, encoding = 'utf-16')
    else :
        df = pd.read_csv(csv, sep=';')
    return df

#retourne la liste privée des doublons de la liste seq 
def makeunique(seq):
    set = {}
    map(set.__setitem__, seq, [])
    return set.keys()

#retourne le dataframe général du repertoire directory
#directory :{client, session, page, compte, commande, souscription}
#/!\ attention à la ram 
#une fois la fonction executée le dataframe est sauvegardée dans le fichier pickle r"W:\L_equipe\s_dataframe_general_root_directory.txt"
#pensez à reset le kernel.
def makegeneraldataframe(directory ):
        if directory == "client" : 
            i=0
        elif directory == "session" : 
            i=1
        elif directory == "page" :
            i=2
        elif directory == "compte" :
            i=3
        elif directory == "commande" :
            i=4
        elif directory == "souscription":
            i=5
        if i < 3 :
            outfile = r'W:\L_equipe\s_dataframe_xiti.txt'
            l_df= pickle.load(open(outfile, "rb"))
            dfs = []
            for j in l_df[i] : 
                dfs.append(makedataframe(j))
            df_g = pd.concat(dfs)
            df_g.to_pickle(r"W:\L_equipe\s_dataframe_general_xiti_"+directory+".pkl")
            #pickle.dump(df_g, open( r"W:\L_equipe\s_dataframe_general_xiti_"+directory+".txt", "wb" ))
            #json.dump(df_g, open( r"W:\L_equipe\s_dataframe_general_xiti_"+directory+".json", "wb" ))
        elif i>= 3 and i<6 :
            outfile = r'W:\L_equipe\s_dataframe_vel.txt'
            l_df= pickle.load(open(outfile, "rb"))
            dfs = []
            for j in l_df[i-3] : 
                dfs.append(makedataframe(j))
            df_g = pd.concat(dfs)
            df_g.to_pickle(r"W:\L_equipe\s_dataframe_general_vel_"+directory+".pkl")
            #pickle.dump(df_g,  open( r"W:\L_equipe\s_dataframe_general_vel_"+directory+".txt", "wb" )) 
            #json.dump(df_g, open( r"W:\L_equipe\s_dataframe_general_vel_"+directory+".json", "wb" ))

        return df_g

## A faire tourner

In [8]:
df_g_page1 =  pd.read_csv(r"Y:\L_equipe\tablesbrutes\Xiti\Pages\pages_xiti-_pages_20150707.csv", sep=';')
df_g_page2 =  pd.read_csv(r"Y:\L_equipe\tablesbrutes\Xiti\Pages\pages_xiti-_pages_20150706.csv", sep=';')

In [9]:
df_g = pd.concat((df_g_page1,df_g_page2))

In [11]:
df_g.to_csv(r"W:\L_equipe\test_page.csv")

In [6]:
df_prod = pd.read_pickle(r"C:\Users\Data Science 5\Desktop\L_equipe\s_dataframe_general_vel_PROD42.pkl")
df_prod.sort_values(by='ExplicitPrice')

,SubscriptionId,ServiceID,SubscriptionCreated,SubscriptionLastUpdated,SubscriptionStatusID,SubscriptionStatus,ServiceTitle,ServiceDescription,ServiceGroup,ServiceGroupTitle,...,ClientUserId,ServiceExpiry,AutoRenew,ExplicitPaymentType,ExplicitPrice,ExplicitCurrency,PriceBandPaymentType,PriceBandAmount,PriceBandCurrency,IsTrial
2940,3919680,11829,05/12/2014 14:48:27,05/03/2015 14:49:10,3,Expired Subscription,Abo_ASO_3_mois_gratuits,Abonnement 3 mois gratuits via ASO Marathon,Abo EQP via Tiers,Abo EQP via Tiers,...,1407543,05/03/2015 14:48:27,0,eWallet,0,EUR,NaN,NaN,NaN,False
744,3963224,11787,10/01/2015 21:21:31,10/04/2015 21:25:30,2,Active Subscription,SFR_Full_Gratuit,Abonnement L'Équipe via SFR : full pris en opt...,Abo EQP via Tiers,Abo EQP via Tiers,...,1436049,10/05/2015 21:25:30,1,eWallet,0,EUR,NaN,NaN,NaN,False
745,3924245,11787,10/12/2014 21:27:06,10/04/2015 21:31:38,2,Active Subscription,SFR_Full_Gratuit,Abonnement L'Équipe via SFR : full pris en opt...,Abo EQP via Tiers,Abo EQP via Tiers,...,1411618,10/05/2015 21:31:38,1,eWallet,0,EUR,NaN,NaN,NaN,False
746,4047093,11787,10/02/2015 21:29:36,10/04/2015 21:31:40,2,Active Subscription,SFR_Full_Gratuit,Abonnement L'Équipe via SFR : full pris en opt...,Abo EQP via Tiers,Abo EQP via Tiers,...,1459689,10/05/2015 21:31:40,1,eWallet,0,EUR,NaN,NaN,NaN,False
747,4047094,11787,10/02/2015 21:30:33,10/04/2015 21:32:41,2,Active Subscription,SFR_Full_Gratuit,Abonnement L'Équipe via SFR : full pris en opt...,Abo EQP via Tiers,Abo EQP via Tiers,...,1459690,10/05/2015 21:32:41,1,eWallet,0,EUR,NaN,NaN,NaN,False
748,4047095,11787,10/02/2015 21:30:36,10/04/2015 21:32:42,2,Active Subscription,SFR_Full_Gratuit,Abonnement L'Équipe via SFR : full pris en opt...,Abo EQP via Tiers,Abo EQP via Tiers,...,1459691,10/05/2015 21:32:42,1,eWallet,0,EUR,NaN,NaN,NaN,False
749,4047097,11787,10/02/2015 21:32:12,10/04/2015 21:33:46,2,Active Subscription,SFR_Full_Gratuit,Abonnement L'Équipe via SFR : full pris en opt...,Abo EQP via Tiers,Abo EQP via Tiers,...,1459692,10/05/2015 21:33:46,1,eWallet,0,EUR,NaN,NaN,NaN,False
750,3924248,11787,10/12/2014 21:35:46,10/04/2015 21:39:08,2,Active Subscription,SFR_Full_Gratuit,Abonnement L'Équipe via SFR : full pris en opt...,Abo EQP via Tiers,Abo EQP via Tiers,...,1411629,10/05/2015 21:39:08,1,eWallet,0,EUR,NaN,NaN,NaN,False
751,4117010,11787,10/04/2015 21:49:39,10/04/2015 21:49:39,2,Active Subscription,SFR_Full_Gratuit,Abonnement L'Équipe via SFR : full pris en opt...,Abo EQP via Tiers,Abo EQP via Tiers,...,1502056,10/05/2015 21:49:39,1,eWallet,0,EUR,NaN,NaN,NaN,False
752,4117012,11787,10/04/2015 21:51:19,10/04/2015 21:51:19,2,Active Subscription,SFR_Full_Gratuit,Abonnement L'Équipe via SFR : full pris en opt...,Abo EQP via Tiers,Abo EQP via Tiers,...,1502058,10/05/2015 21:51:19,1,eWallet,0,EUR,NaN,NaN,NaN,False
753,4075106,11787,10/03/2015 21:57:29,10/04/2015 21:58:27,2,Active Subscription,SFR_Full_Gratuit,Abonnement L'Équipe via SFR : full pris en opt...,Abo EQP via Tiers,Abo EQP via Tiers,...,1478805,10/05/2015 21:58:27,1,eWallet,0,EUR,NaN,NaN,NaN,False
754,3924265,11787,10/12/2014 21:57:13,10/04/2015 22:01:40,2,Active Subscription,SFR_Full_Gratuit,Abonnement L'Équipe via SFR : full pris en opt...,Abo EQP via Tiers,Abo EQP via Tiers,...,1310513,10/05/2015 22:01:40,1,eWallet,0,EUR,NaN,NaN,NaN,False
755,4075971,11787,12/03/2015 11:05:51,10/04/2015 22:02:04,5,Cancelled By User,SFR_Full_Gratuit,Abonnement L'Équipe via SFR : full pris en opt...,Abo EQP via Tiers,Abo EQP via Tiers,...,1479991,10/04/2015 22:02:04,0,eWallet,0,EUR,NaN,NaN,NaN,False
756,4090171,11787,19/03/2015 09:09:01,10/04/2015 22:03:09,5,Cancelled By User,SFR_Full_Gratuit,Abonnement L'Équipe via SFR : full pris en opt...,Abo EQP via Tiers,Abo EQP via Tiers,...,1485411,10/04/2015 22:03:09,0,eWallet,0,EUR,NaN,NaN,NaN,False
757,4075980,11787,12/03/2015 11:14:15,10/04/2015 22:09:39,5,Cancelled By User,SFR_Full_Gratuit,Abonnement L'Équipe via SFR : full pris en opt...,Abo EQP via Tiers,Abo EQP via Tiers,...,1480002,10/04/2015 22:09:39,0,eWallet,0,EUR,NaN,NaN,NaN,False
758,3924266,11787,10/12/2014 22:05:58,10/04/2015 22:10:00,2,Active Subscription,SFR_Full_Gratuit,Abonnement L'Équipe via SFR : full pris en opt...,Abo EQP via Tiers,Abo EQP via Tiers,...,1411658,10/05/2015 22:10:00,1,eWallet,0,EUR,NaN,NaN,NaN,False
759,4075570,11787,11/03/2015 17:46:02,10/04/2015 22:13:03,5,Cancelled By User,SFR_Full_Gratuit,Abonnement L'Équipe via SFR : full pris en opt...,Abo EQP via Tiers,Abo EQP via Tiers,...,1479152,10/04/2015 22:13:03,0,eWallet,0,EUR,NaN,NaN,NaN,False
760,3945275,11787,27/12/2014 22:02:17,10/04/2015 22:13:33,5,Cancelled By User,SFR_Full_Gratuit,Abonnement L'Équipe via SFR : full pris en opt...,Abo EQP via Tiers,Abo EQP via Tiers,...,1422700,10/04/2015 22:13:33,0,eWallet,0,EUR,NaN,NaN,NaN,False
761,4076037,11787,12/03/2015 12:47:17,10/04/2015 22:14:09,5,Cancelled By User,SFR_Full_Gratuit,Abonnement L'Équipe via SFR : full pris en opt...,Abo EQP via Tiers,Abo EQP via Tiers,...,1480062,10/04/2015 22:14:10,0,eWallet,0,EUR,NaN,NaN,NaN,False
762,4078988,11787,13/03/2015 12:02:22,10/04/2015 22:14:40,5,Cancelled By User,SFR_Full_Gratuit,Abonnement L'Équipe via SFR : full pris en opt...,Abo EQP via Tiers,Abo EQP via Tiers,...,1480747,10/04/2015 22:14:40,0,eWallet,0,EUR,NaN,NaN,NaN,False
763,4117031,11787,10/04/2015 22:17:05,10/04/2015 22:17:05,2,Active Subscription,SFR_Full_Gratuit,Abonnement L'Équipe via SFR : full pris en opt...,Abo EQP via Tiers,Abo EQP via Tiers,...,1502067,10/05/2015 22:17:05,1,eWallet,0,EUR,NaN,NaN,NaN,False
764,4076005,11787,12/03/2015 11:47:38,10/04/2015 22:22:03,5,Cancelled By User,SFR_Full_Gratuit,Abonnement L'Équipe via SFR : full pris en opt...,Abo EQP via Tiers,Abo EQP via Tiers,...,1480030,10/04/2015 22:22:04,0,eWallet,0,EUR,NaN,NaN,NaN,False
765,4117037,11787,10/04/2015 22:25:57,10/04/2015 22:25:57,2,Active Subscription,SFR_Full_Gratuit,Abonnement L'Équipe via SFR : full pris en opt...,Abo EQP via Tiers,Abo EQP via Tiers,...,548919,10/05/2015 22:25:57,1,eWallet,0,EUR,NaN,NaN,NaN,False
767,3871678,11787,20/10/2014 14:08:46,10/04/2015 22:31:29,5,Cancelled By User,SFR_Full_Gratuit,Abonnement L'Équipe via SFR : full pris en opt...,Abo EQP via Tiers,Abo EQP via Tiers,...,1366987,10/04/2015 22:31:29,0,eWallet,0,EUR,NaN,NaN,NaN,False
743,3924236,11787,10/12/2014 21:19:14,10/04/2015 21:24:27,2,Active Subscription,SFR_Full_Gratuit,Abonnement L'Équipe via SFR : full pris en opt...,Abo EQP via Tiers,Abo EQP via Tiers,...,1411607,10/05/2015 21:24:27,1,eWallet,0,EUR,NaN,NaN,NaN,False
768,3871869,11787,20/10/2014 17:41:22,10/04/2015 22:36:09,5,Cancelled By User,SFR_Full_Gratuit,Abonnement L'Équipe via SFR : full pris en opt...,Abo EQP via Tiers,Abo EQP via Tiers,...,1367100,10/04/2015 22:36:09,0,eWallet,0,EUR,NaN,NaN,NaN,False
742,4116991,11787,10/04/2015 21:19:37,10/04/2015 21:19:37,2,Active Subscription,SFR_Full_Gratuit,Abonnement L'Équipe via SFR : full pris en opt...,Abo EQP via Tiers,Abo EQP via Tiers,...,1502046,10/05/2015 21:19:37,1,eWallet,0,EUR,NaN,NaN,NaN,False
740,3963211,11787,10/01/2015 21:11:28,10/04/2015 21:14:30,2,Active Subscription,SFR_Full_Gratuit,Abonnement L'Équipe via SFR : full pris en opt...,Abo EQP via Tiers,Abo EQP via Tiers,...,1436040,10/05/2015 21:14:30,1,eWallet,0,EUR,NaN,NaN,NaN,False
715,3963080,11787,10/01/2015 20:11:47,10/04/2015 20:13:45,2,Active Subscription,SFR_Full_Gratuit,Abonnement L'Équipe via SFR : full pris en opt...,Abo EQP via Tiers,Abo EQP via Tiers,...,1435963,10/05/2015 20:13:45,1,eWallet,0,EUR,NaN,NaN,NaN,False
716,4075059,11787,10/03/2015 20:13:47,10/04/2015 20:14:53,2,Active Subscription,SFR_Full_Gratuit,Abonnement L'Équipe via SFR : full pris en opt...,Abo EQP via Tiers,Abo EQP via Tiers,...,1478704,10/05/2015 20:14:53,1,eWallet,0,EUR,NaN,NaN,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,3833710,11749,27/09/2014 01:46:09,18/01/2015 00:00:26,3,Expired Subscription,Abo_1_an_168€,Abonnement 1 an à 168€,Abos EQP,Abo EQP,...,250243,18/01/2015 00:00:00,0,eWallet,168,EUR,NaN,NaN,NaN,False
0,3827312,11749,26/09/2014 16:22:04,23/02/2015 00:01:11,3,Expired Subscription,Abo_1_an_168€,Abonnement 1 an à 168€,Abos EQP,Abo EQP,...,904792,23/02/2015 00:00:00,0,eWallet,168,EUR,NaN,NaN,NaN,False
223,3826247,11749,26/09/2014 11:57:25,13/10/2014 12:09:33,1,Cancelled By Customer Support Agent,Abo_1_an_168€,Abonnement 1 an à 168€,Abos EQP,Abo EQP,...,979182,13/10/2014 12:09:34,0,eWallet,168,EUR,NaN,NaN,NaN,False
1,3830948,11749,27/09/2014 00:50:51,23/02/2015 00:01:11,3,Expired Subscription,Abo_1_an_168€,Abonnement 1 an à 168€,Abos EQP,Abo EQP,...,552531,23/02/2015 00:00:00,0,eWallet,168,EUR,NaN,NaN,NaN,False
189,3836285,11749,27/09/2014 02:04:42,14/06/2015 08:07:22,2,Active Subscription,Abo_1_an_168€,Abonnement 1 an à 168€,Abos EQP,Abo EQP,...,1273923,14/06/2016 08:07:18,0,eWallet,168,EUR,NaN,NaN,NaN,False
354,3829015,11749,26/09/2014 23:17:32,06/02/2015 11:48:22,2,Active Subscription,Abo_1_an_168€,Abonnement 1 an à 168€,Abos EQP,Abo EQP,...,737645,06/02/2016 11:48:19,0,eWallet,168,EUR,NaN,NaN,NaN,False
270,3828453,11749,26/09/2014 21:33:09,30/12/2014 09:26:06,2,Active Subscription,Abo_1_an_168€,Abonnement 1 an à 168€,Abos EQP,Abo EQP,...,799216,30/12/2015 09:26:03,0,eWallet,168,EUR,NaN,NaN,NaN,False
218,3834999,11749,27/09/2014 01:57:22,13/10/2014 12:08:50,1,Cancelled By Customer Support Agent,Abo_1_an_168€,Abonnement 1 an à 168€,Abos EQP,Abo EQP,...,1309248,13/10/2014 12:08:51,0,eWallet,168,EUR,NaN,NaN,NaN,False
3,3841603,11749,27/09/2014 02:26:12,18/04/2015 00:00:45,3,Expired Subscription,Abo_1_an_168€,Abonnement 1 an à 168€,Abos EQP,Abo EQP,...,1225225,18/04/2015 00:00:00,0,eWallet,168,EUR,NaN,NaN,NaN,False
87,3831635,11749,27/09/2014 01:05:41,14/10/2014 05:45:15,2,Active Subscription,Abo_1_an_168€,Abonnement 1 an à 168€,Abos EQP,Abo EQP,...,474060,14/10/2015 05:45:11,0,eWallet,168,EUR,NaN,NaN,NaN,False
374,3833302,11749,27/09/2014 01:39:56,08/10/2014 13:37:04,2,Active Subscription,Abo_1_an_168€,Abonnement 1 an à 168€,Abos EQP,Abo EQP,...,325,30/03/2015 00:00:00,1,eWallet,168,EUR,NaN,NaN,NaN,False
138,3846545,11749,27/09/2014 03:18:59,10/10/2014 00:10:42,3,Expired Subscription,Abo_1_an_168€,Abonnement 1 an à 168€,Abos EQP,Abo EQP,...,1076456,10/10/2014 00:00:00,0,eWallet,168,EUR,NaN,NaN,NaN,False
2,3828542,11749,26/09/2014 21:47:14,18/04/2015 00:00:44,3,Expired Subscription,Abo_1_an_168€,Abonnement 1 an à 168€,Abos EQP,Abo EQP,...,787117,18/04/2015 00:00:00,0,eWallet,168,EUR,NaN,NaN,NaN,False
1,3829854,11749,27/09/2014 00:28:22,12/05/2015 00:00:22,3,Expired Subscription,Abo_1_an_168€,Abonnement 1 an à 168€,Abos EQP,Abo EQP,...,663590,12/05/2015 00:00:00,0,eWallet,168,EUR,NaN,NaN,NaN,False
0,3826471,11749,26/09/2014 12:54:16,20/06/2015 00:01:14,3,Expired Subscription,Abo_1_an_168€,Abonnement 1 an à 168€,Abos EQP,Abo EQP,...,965860,20/06/2015 00:00:00,0,eWallet,168,EUR,NaN,NaN,NaN,False
1,3831590,11749,27/09/2014 01:04:39,20/06/2015 00:01:15,3,Expired Subscription,Abo_1_an_168€,Abonnement 1 an à 168€,Abos EQP,Abo EQP,...,477580,20/06/2015 00:00:00,0,eWallet,168,EUR,NaN,NaN,NaN,False
3,3841213,11749,27/09/2014 02:22:51,12/05/2015 00:00:22,3,Expired Subscription,Abo_1_an_168€,Abonnement 1 an à 168€,Abos EQP,Abo EQP,...,1239407,12/05/2015 00:00:00,0,eWallet,168,EUR,NaN,NaN,NaN,False
36,3832765,11749,27/09/2014 01:26:44,09/10/2014 00:05:00,3,Expired Subscription,Abo_1_an_168€,Abonnement 1 an à 168€,Abos EQP,Abo EQP,...,360113,09/10/2014 00:00:00,0,eWallet,168,EUR,NaN,NaN,NaN,False
2,3842567,11749,27/09/2014 02:35:40,07/03/2015 00:01:20,3,Expired Subscription,Abo_1_an_168€,Abonnement 1 an à 168€,Abos EQP,Abo EQP,...,1195814,07/03/2015 00:00:00,0,eWallet,168,EUR,NaN,NaN,NaN,False
116,3893616,11749,12/11/2014 05:48:45,12/11/2014 05:48:45,2,Active Subscription,Abo_1_an_168€,Abonnement 1 an à 168€,Abos EQP,Abo EQP,...,1361691,12/11/2015 05:48:45,0,eWallet,168,EUR,NaN,NaN,NaN,False
1,3842550,11749,27/09/2014 02:35:35,07/03/2015 00:01:19,3,Expired Subscription,Abo_1_an_168€,Abonnement 1 an à 168€,Abos EQP,Abo EQP,...,1196747,07/03/2015 00:00:00,0,eWallet,168,EUR,NaN,NaN,NaN,False
0,3831593,11749,27/09/2014 01:04:42,07/03/2015 00:01:19,3,Expired Subscription,Abo_1_an_168€,Abonnement 1 an à 168€,Abos EQP,Abo EQP,...,477359,07/03/2015 00:00:00,0,eWallet,168,EUR,NaN,NaN,NaN,False
1,3828509,11749,26/09/2014 21:41:13,18/04/2015 00:00:44,3,Expired Subscription,Abo_1_an_168€,Abonnement 1 an à 168€,Abos EQP,Abo EQP,...,791508,18/04/2015 00:00:00,0,eWallet,168,EUR,NaN,NaN,NaN,False
73,3846516,11749,27/09/2014 03:18:31,14/10/2014 00:08:21,3,Expired Subscription,Abo_1_an_168€,Abonnement 1 an à 168€,Abos EQP,Abo EQP,...,1077978,14/10/2014 00:00:00,0,eWallet,168,EUR,NaN,NaN,NaN,False
72,3846513,11749,27/09/2014 03:18:31,14/10/2014 00:08:21,3,Expired Subscription,Abo_1_an_168€,Abonnement 1 an à 168€,Abos EQP,Abo EQP,...,1078112,14/10/2014 00:00:00,0,eWallet,168,EUR,NaN,NaN,NaN,False
3,3845065,11737,27/09/2014 03:02:27,11/11/2014 00:01:39,3,Expired Subscription,Abo_1_an_228€_tablette,Abonnement Salon d'1 an à 228€ avec un tablett...,Abos EQP,Abo EQP,...,1100253,11/11/2014 00:00:00,0,eWallet,228,EUR,NaN,NaN,NaN,False
6,3845189,11737,27/09/2014 03:06:37,07/11/2014 00:01:23,3,Expired Subscription,Abo_1_an_228€_tablette,Abonnement Salon d'1 an à 228€ avec un tablett...,Abos EQP,Abo EQP,...,1095779,07/11/2014 00:00:00,0,eWallet,228,EUR,NaN,NaN,NaN,False
4,3829806,11737,27/09/2014 00:27:19,04/03/2015 00:01:13,3,Expired Subscription,Abo_1_an_228€_tablette,Abonnement Salon d'1 an à 228€ avec un tablett...,Abos EQP,Abo EQP,...,665075,04/03/2015 00:00:00,0,eWallet,228,EUR,NaN,NaN,NaN,False
5,3845149,11737,27/09/2014 03:05:05,07/11/2014 00:01:23,3,Expired Subscription,Abo_1_an_228€_tablette,Abonnement Salon d'1 an à 228€ avec un tablett...,Abos EQP,Abo EQP,...,1096440,07/11/2014 00:00:00,0,eWallet,228,EUR,NaN,NaN,NaN,False
6,3845209,11737,27/09/2014 03:06:56,03/12/2014 00:01:15,3,Expired Subscription,Abo_1_an_228€_tablette,Abonnement Salon d'1 an à 228€ avec un tablett...,Abos EQP,Abo EQP,...,1094925,03/12/2014 00:00:00,0,eWallet,228,EUR,NaN,NaN,NaN,False

In [13]:
#df_prod['SubscriptionCreated'] = pd.to_datetime(df_prod['SubscriptionCreated'], format='%d/%m/%Y %H:%M:%S')
df_prod['derniere_visite'] = pd.to_datetime(df_prod['derniere_visite'])

In [14]:
df_prod.head(6)

,fileid,id_site,id_client,premiere_visite,derniere_visite,visites,pages_vues
0,_clients_20130909_20140910.csv,413580,22833,2014-09-09,2014-09-09,1,1
1,_clients_20130909_20140910.csv,413580,94402,2014-08-03,2014-09-09,1,23
2,_clients_20130909_20140910.csv,413580,132365,2014-07-31,2014-09-09,2,3
3,_clients_20130909_20140910.csv,413580,643365,2014-08-08,2014-09-09,1,1
4,_clients_20130909_20140910.csv,413580,705303,2014-08-31,2014-09-09,8,30
5,_clients_20130909_20140910.csv,413580,715929,2014-08-04,2014-09-09,1,1

In [6]:
l =[1,2,3,4,5]
l2 = [1,6,9]
l3 = [1,6]
l4 = l2
print cmp(l,l2)
print cmp(l2,l)
print cmp(l2,l3)
print cmp(l2,l4)

-1
1
1
0

In [ ]:
df = pd.read_csv(r'V:\Tables_Sas\L_Equipe\Projet_01042016\tables_brutes\clients_premium_2015')
clients_premium_2015

In [2]:
df = pd.read_csv(r'V:\L_Equipe\Projet_01042016\tables_brutes\clients_premium_2015.csv')

In [3]:
d = df.id_client.unique()

In [6]:
data = pd.DataFrame(d)

In [21]:
data.rename(columns={0:'id_client'}, inplace=True)

In [26]:
data.to_csv(r'V:\L_Equipe\Projet_01042016\tables_brutes\liste_clients_premium_2015.csv', encoding ='utf-8', index=False, index_label=False)